server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/notification
    username: springmicr
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"


